[project]
name = "kubernetes-cross-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cerberus>=1.3.8",
    "kubernetes>=35.0.0",
    "pyyaml>=6.0.3",
    "tabulate>=0.9.0",
    "tqdm>=4.67.3",
]
